### ISSUE TITLE
Feature request: Remove template on sls remove

### ISSUE THREAD

**Issue by LarsPede** [Enase/serverless-ses-template#141]
Hi @Enase 

Absolutely amazing plugin - makes all this templating so much more simple to handle.
I think this might be a feature request? or at least a discussion in terms of how one might do a workaround.

_The current behaviour:_
`sls deploy` deploys the template and can send emails based on it.
`sls remove` does not remove the template in the cleanup step.

_The feature request:_
`sls deploy` deploys the template and can send emails based on it.
`sls remove` does removes the template in the cleanup step.

_Version_
serverless: **3.32.2**
@haftahave/serverless-ses-template: **5.0.2**
ESM/commonJS: **commonJS**

**Comment by Enase** [comment]
@LarsPede Good idea, I will definitely add it next version. Fell free to share any other ideas if you have it. Thanks for your feedback!

**Comment by Enase** [comment]
Hi @LarsPede  New versions are published, thanks for your effort and feel free to use:
ESM: [6.1.0](https://github.com/haftahave/serverless-ses-template/releases/tag/6.1.0)
CommonJS: [5.1.0](https://github.com/haftahave/serverless-ses-template/releases/tag/5.1.0)
Pls report issues if any.
